spring:
  application:
    name: ms-consumer-movice-ribbon #使用小写

logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.daniel.cloud: debug
    
server:
  port: 7901
  
eureka:
  client:
    service-url: 
      #defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://eureka:eureka123456@127.0.0.1:8761/eureka
  instance: 
    prefer-ip-address: true 
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

# 用户微服务的策略
ms-provider-user-ribbon: 
  ribbon: 
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
