
spring:
  application:
    name: ms-discovery-eureka-peer2

logging:
  level:
    root: info
    com.daniel.cloud: debug
    
server:
  port: 8762 

security:
  basic:
    enabled: true
  user: 
    name: eureka
    password: eureka123456

eureka:
  instance: 
    hostname: peer2.eureka.com
  client:
    healthcheck: 
      enabled: true 
    register-with-eureka: false #只当做eureka server
    fetch-registry: false #只当做eureka server
    service-url: 
      defaultZone: http://eureka:eureka123456@peer1.eureka.com:8761/eureka/